[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[project]
name = "pytsg"
version = "0.5.0"
description = "Library to read .tsg file package"
license = "MIT"
readme = "README.md"
dependencies = [
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "simplejpeg>=1.9.0",
    "scipy>=1.16.0",
    'dhcomp',
]
keywords = [
    "tsg",
    "hyperspectral",
    "drillcore",
    "mineralogy",
    "data",
    "HyLogger",
    "spectroscopy",
]
requires-python = ">= 3.12"
authors = [
    { name = "Ben Chi", email = "ben@fractalgeoanalytics.com" },
    { name = "Geoscience Data Integrations Team - GSWA", email = "gdi.contact@dmpe.wa.gov.au" },
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Software Development',
    'Topic :: Scientific/Engineering',
    'Operating System :: OS Independent',
]

[project.optional-dependencies]
bigfile = ["zarr>2.16.1"]

[project.urls]
Repository = "https://github.com/Geological-Survey-of-Western-Australia/pytsg"
"Bug Tracker" = "https://github.com/Geological-Survey-of-Western-Australia/pytsg/issues"

[dependency-groups]
dev = [
    "black",
    "Sphinx>=9.0.0",
    "sphinx-rtd-theme>=3.1.0",
    "sphinx-gallery>=0.21.0",
    "myst-parser>=5.1.0",
    "sphinx-autodoc-typehints>=3.13.4",
    "matplotlib>=3.11.1",
    "sphinx-autobuild>=2025.8.25",
    "ruff>=0.16.6",
    "ty>=0.0.78",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pyarrow>=25.0.1",
    "sphinx-llm>=1.1.0",
]

[tool.uv]
# sphinx-llm includes the README.md in llms.txt from the locally installed
# version of pytsg. Include it as a cache key to invalidate the build when
# it changes or you won't be able to pick up new changes when testing locally.
cache-keys = [{ file = "pyproject.toml" }, { file = "README.md" }]

[tool.ruff]
line-length = 110

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
select = ["B", "D", "DOC202", "DOC102", "DOC201", "E", "F", "Q", "W", "I"]
ignore = ["D203", "D212"]

[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-var-parameters = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["B", "D", "DOC202", "DOC102", "DOC201"]
"**/examples/*" = ["B", "D", "DOC202", "DOC102", "DOC201"]
"**/doc/source/conf.py" = ["B", "D", "DOC202", "DOC102", "DOC201"]
"**/src/pytsg/parse_tsg.py" = ["DOC202", "DOC102", "DOC201"]

[tool.coverage.run]
omit = [
    "tests/*",
    "**/test_*.py",
]
