[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[project]
name = "pytsg"
version = "0.5.0"
description = "Library to read .tsg file package"
license = "MIT"
readme = "README.md"
dependencies = [
    "numpy>1.23",
    'pandas>1.4.3',
    "simplejpeg>1.6.5",
    "scipy>1.11.4",
    'dhcomp',
]
keywords = [
    "tsg",
    "hyperspectral",
    "drillcore",
    "mineralogy",
    "data",
    "HyLogger",
    "spectroscopy",
]
requires-python = ">= 3.12"
authors = [
    { name = "Ben Chi", email = "ben@fractalgeoanalytics.com" },
    { name = "Geoscience Data Integrations Team - GSWA", email = "gdi.contact@dmpe.wa.gov.au" },
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Software Development',
    'Topic :: Scientific/Engineering',
    'Operating System :: OS Independent',
]

[project.optional-dependencies]
bigfile = ["zarr>2.16.1"]

[project.urls]
Repository = "https://github.com/Geological-Survey-of-Western-Australia/pytsg"
"Bug Tracker" = "https://github.com/Geological-Survey-of-Western-Australia/pytsg/issues"

[dependency-groups]
dev = [
    "black",
    "Sphinx>=9.0.0",
    "sphinx-rtd-theme>=3.1.0",
    "sphinx-gallery>=0.21.0",
    "myst-parser>=5.1.0",
    "sphinx-autodoc-typehints>=3.13.4",
    "matplotlib>=3.11.1",
]
